apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: pgp-proofs
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: drgrove/pgp-proofs
    digest: sha256:4a3bf94ee6ea591861bda237eccd743fa148be4e2a8da77e50433145ed41dbfc
